#!/usr/bin/env python
import rospy
from sensor_msgs.msg import Range

def callback(data):
    if data.range >= 15:
        print "too far"
    print (data.range)
   
def listener():
    rospy.init_node('listener', anonymous=True)
    print "1"
    rospy.Subscriber("/robot/range/right_hand_range/state", Range, callback)

    # spin() simply keeps python from exiting until this node is stopped
    rospy.spin()
       
listener()
